name: wkmobile
description: Polska aplikacja fitnessowo-społecznościowa - WK Mobile
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  provider: ^6.0.5

  # FIREBASE (CORE + AUTH + DB + STORAGE + PUSH)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.7.10

  # SOCIAL LOGIN PROVIDERS
  google_sign_in: ^5.4.3
  flutter_facebook_auth: ^7.1.0
  sign_in_with_apple: ^4.1.0

  # MEDIA / UPLOAD
  image_picker: ^1.1.2

  # UI I NARZĘDZIA
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.2

  # CHARTS & POWIADOMIENIA
  fl_chart: ^0.66.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

  # PDF & PRINT
  printing: ^5.11.2
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutterfire_cli: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/challenges.json
    - assets/icons/
    - assets/images/
